### ISSUE TITLE
Bind to diffrent R.layout.example.xml

### ISSUE THREAD

**Issue by romansigrist** [Wrdlbrnft/SortedListAdapter#2]
Hi!
I'm not familiar with DataBinding. How can i bind to diffrent xml layouts? Normally i can change the layout xml in the onCreateViewHolder function:
`inflater.inflate(R.layout.example, parent, false);`
How can i change the ViewType and the ViewHolder based on the Model.getName() function or other criteria? I'm very open for good suggestions.
Thx for your help.

**Comment by Wrdlbrnft** [comment]
I'm not sure what you are asking about. You don't have to use DataBinding with SortedListAdapter. If you are uncomfortable with it, you can still inflate a view like usual and do all the data binding yourself. If you want to learn more about data binding start here: https://developer.android.com/topic/libraries/data-binding/index.html

**Comment by romansigrist** [comment]
Yes, i think i let it go for the moment. All i see in the onCreateViewHolder is:
```
final ModelBinding binding = ModelBinding.inflate(inflater, parent, false);
return new FilesHolder(binding, mListener);
```
And out of nowhere the ActivityMainBinding is broken again. Thx for your reply.
